# This file was generated by GoReleaser. DO NOT EDIT.
cask "edrolo" do
  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "0297a6df7280e1ad56e1119640971ada89fd0ab6aff2148c3418153cac6d6e66"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6098ec27def7f743218af377fa8f1f7e2aeafd0a295bbd883622b460cfa0c4b"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84372f595e5acb50994db6e780b3fdb6e2fa70445c19765b3c04fd1ff6aace63"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "952eecb135e0e31c66faa9af90aec2a709bffaa96fa1915c11235499823a04f9"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_amd64.tar.gz"
    end
  end

  name "edrolo"
  desc "Edrolo CLI -- programmatic access to the Edrolo API"
  homepage "https://github.com/Edrolo/edrolo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edrolo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edrolo"]
    end
  end

  # No zap stanza required
end
