# This file was generated by GoReleaser. DO NOT EDIT.
cask "edrolo" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "679d966e68348b8f473f8b32488e9fcf77c2bfc0003589e1fadedd4024d5a7fa"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c222943b9f67ae3b2fcd3ea1f2ff40d6b62d553218cf23f21173422067cb0fa"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6221b1bc72daa16386fe9df541ac29759e0db8832fa81d5d8d5b213ac00961e4"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8bc5d048e7417729fe905f6058c2ae8b0475a238a39b9dff292effccbe062c3f"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_amd64.tar.gz"
    end
  end

  name "edrolo"
  desc "Edrolo CLI -- programmatic access to the Edrolo API"
  homepage "https://github.com/Edrolo/edrolo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edrolo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edrolo"]
    end
  end

  # No zap stanza required
end
