# This file was generated by GoReleaser. DO NOT EDIT.
cask "edrolo" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "17f01622b4111f69438f473e2960a06ea8df151046a9c277c0d96a02d0ba8919"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "899e7363f0751e44e8e02c74c16ff4edb3121ae8a8b3d78c5f576e9de6f0b5e4"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4862ecb0afe91ea80bf980e029a1e3df20041a0f465998029cc3fdb99ec55b8f"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06eac20d541979f9b401e5cdcabcc779feb40c5ec5326bc1893cc26da26496f0"
      url "https://github.com/Edrolo/edrolo-cli/releases/download/v#{version}/edrolo_linux_amd64.tar.gz"
    end
  end

  name "edrolo"
  desc "Edrolo CLI -- programmatic access to the Edrolo API"
  homepage "https://github.com/Edrolo/edrolo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "edrolo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/edrolo"]
    end
  end

  # No zap stanza required
end
